[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = ""

# A GitHub oauth application for this instance of homu:
app_client_id = ""
app_client_secret = ""

[git]

# Use the local Git command. Required to use some advanced features. It also
# speeds up Travis by reducing temporary commits
#local_git = false

# SSH private key. Needed only when the local Git command is used
#ssh_key = """
#"""

[web]

# The port homu listens on
port = 54856

# An example configuration for repository (there can be many of these)
[repo.NAME]

# github.com/<owner>/<name>
owner = ""
name = ""

# who has r+ rights?
reviewers = ["barosl", "graydon"]

# who has 'try' rights? (try, retry, force, clean, prioritization)
try_users = []

# Keep the commit history linear. Requires the local Git command
#linear = false

# Auto-squash commits. Requires the local Git command
#autosquash = true

## branch names (these settings here are the defaults)
#[repo.NAME.branch]
#
#auto = "auto"
#try = "try"
#rollup = "rollup"

[repo.NAME.github]

# arbitrary secret (e.g. openssl rand -hex 20)
secret = ""

## Use buildbot for running tests
#[repo.NAME.buildbot]
#
#url = ""
#secret = ""
#
#builders = ["auto-linux", "auto-mac"]
#try_builders = ["try-linux", "try-mac"]
#
#username = ""
#password = ""

## Use travis for running tests
#[repo.NAME.travis]
#
## found under <https://travis-ci.org/profile/info>.
#token = ""

## Use the Status API
#[repo.NAME.status]
#
## String label set by status updates
#context = ""
